README.md
gatsby-config.js
package.json
src/templates/blog-post.css
yarn.lock

[ISSUE #7] Add Auto Linking Headers

---

README.md
src/templates/blog-post.js

[ISSUE #17] Add SEO to blog posts

---

src/pages/blog-posts/002-what-the-reagent-component.md

002 - Publish What the Reagent Component?!

---

gatsby-config.js
package.json
src/pages/index.js
yarn.lock

[ISSUE #27] Add rss feed

---

README.md

Resolves #25   Credit where credit is do :) Thank you both so much!

[ISSUE #25] Add to README Special Thanks

---

README.md
gatsby-config.js
src/pages/blog-posts/000-deploy-clojurescript-to-github-pages.md
src/pages/blog-posts/001-creating-a-clojurescript-project-from-scratch.md
src/pages/blog-posts/002-what-the-reagent-component.md
src/pages/index.js
src/templates/blog-post.js

[ISSUE #20] Add SEO keywords to blog posts

---

gatsby-config.js
src/pages/index.js

Resolves #30 
I wanted to keep these things outside of the code.  Further, it was annoying me that the rss feed link would have to be specified too far apart which means I would likely forget where the other definition is

[ISSUE #30] Move footerlink to gatsby-config

---

src/templates/blog-post.css

[ISSUE #26] Fix inline styles for inline-code highlighting

---

src/templates/blog-post.css

[ISSUE #16] Soften active footnote background colour

---

src/pages/blog-posts/002-what-the-reagent-component.md

Resolves #38 
Round of grammar, spelling and overall flow improvements.

[ISSUE #38] 002 - edit round 1

---

README.md
package.json
yarn.lock

ISSUE #44 - Bump blog deps

---

src/pages/blog-posts/000-deploy-clojurescript-to-github-pages.md

Cleanup blog post 000 intro + keywords

---

src/pages/blog-posts/005-deploy-clojurescript-on-nginx.md

October 27 was the date I first posted this article for feedback

Update blog post 005 original publish date

---

src/pages/blog-posts/006-clojure-text-editors.md

Update Blog Post - 006 - grammar

---

src/pages/blog-posts/006-clojure-text-editors.md

Resolves #60 
Add more details for configuring setup and links to the youtube series.

Issue #60 - Improve Clojure Text Editors post

---

gatsby-config.js

Add social media link - footer - Youtube

---

package.json
yarn.lock

Resolve #65 No functionality changed, just a bump in the versions

ISSUE #65 Bump dependency version

---

gatsby-config.js
package.json
src/pages/blog-posts/007-reagent-and-hiccup.md
yarn.lock

007 - Publish Blog Post - Reagent and Hiccup

---

src/pages/blog-posts/001-creating-a-clojurescript-project-from-scratch.md

001 - Update Post - ClojureScript QuickStart

---

src/pages/blog-posts/006-clojure-text-editors.md

006 - Update Post - Clojure Text Editors

---

src/pages/blog-posts/002-what-the-reagent-component.md

002 - Update post - Add footnote on modified pattern

---

src/pages/blog-posts/003-testing-clojurescript.md

003 - Update post - Bump versions to latest

---

src/pages/blog-posts/003-testing-clojurescript.md
src/pages/blog-posts/004-reloadable-code.md
src/pages/blog-posts/005-deploy-clojurescript-on-nginx.md

Some of the links to athomasoriginal github repo were incorrect

Update posts - 003, 004, 005

---

src/styles/app.css

ISSUE #77 - Feels cleaner that putting them side-by-side

Refresh 2020 - stack logo and nav menu

---

src/pages/blog-posts/009-what-are-the-clojure-tools.md

ISSUE #106 hopefully improved the flow and clarity of the post.  The
areas changed were ones I felt had duplicated or missed some points

[ISSUE 106] Improve Clojure Tools Post

---

src/pages/blog-posts/007-reagent-and-hiccup.md

ISSUE #92 Update Reagent examples to 1.0.0 API

---

src/pages/blog-posts/010-rich-comments.md

[issue #114] Update Post - 010 - Add two additional discard comment examples

---

README.md

Update Readme - Add Code Block Documentation

---

README.md

[ISSUE #69] Update README - cleanup frontmatter section

---

src/pages/blog-posts/009-what-are-the-clojure-tools.md

[ISSUE #145] Update Blog Post - CLI Tools - monorepo footnote

---

src/pages/blog-posts/006-clojure-text-editors.md

- Update footnote link
- Cut down lots of useless intro

[ISSUE #152] Update Blog Post - 006  - CLJ Editors

---

src/pages/blog-posts/000-deploy-clojurescript-to-github-pages.md
src/pages/blog-posts/001-creating-a-clojurescript-project-from-scratch.md
src/pages/blog-posts/003-testing-clojurescript.md
src/pages/blog-posts/005-deploy-clojurescript-on-nginx.md

New versionfs of clojure, cljs, figwheel and create-reagent-app

[ISSUE #154] Update Blog Posts - Deps

---

src/posts/006-clojure-text-editors.md

[ISSUE #161] Update Post - 006 - Replace footnote w/ inline link

---

.eleventy.js
src/css/styles.css
src/posts/009-what-are-the-clojure-tools.md

Been meaning to update this for a while.  Some of the goals in revising is aligning better to Clojure nomenclature and include information about `-T` and `tools.build` as well as just cleaning up the flow of the post.

[ISSUE #178] Update Clojure Tools Blog

---

.eleventy.js
package.json
src/posts/002-what-the-reagent-component.md
src/posts/004-reloadable-code.md
src/posts/010-rich-comments.md

We're a bit early, but I wanted to jump on this now as I happened to have a spare moment and wanted to see what this update process looks like.

Migrate to Eleventy 1.0

---

package.json
src/_data/site.json
src/about.njk
src/css/styles.css
src/subscribe.njk

[ISSUE #160] Add Link Page
